# Generated by Django 5.0.3 on 2024-05-05 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklist', '0007_firmware_usergroup_device_action_devicesetting_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='analog_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='digital_value',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='io_address',
            field=models.CharField(default='0.0.0.0', max_length=255),
        ),
        migrations.AddField(
            model_name='device',
            name='protocol',
            field=models.CharField(default='opc ua', max_length=255),
        ),
    ]
