# Generated by Django 5.0.3 on 2024-05-16 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booklist', '0012_alter_device_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'ordering': ['name'], 'verbose_name': 'Device', 'verbose_name_plural': 'Device'},
        ),
        migrations.AlterModelTable(
            name='device',
            table='Device',
        ),
    ]
