# Generated by Django 5.0.3 on 2024-05-21 05:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklist', '0014_alter_device_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['name'], 'verbose_name': 'Room', 'verbose_name_plural': 'Room'},
        ),
        migrations.RemoveField(
            model_name='room',
            name='device',
        ),
        migrations.AddField(
            model_name='device',
            name='room',
            field=models.ForeignKey(default=uuid.uuid4, null=True, on_delete=django.db.models.deletion.CASCADE, to='booklist.room'),
        ),
        migrations.AddField(
            model_name='room',
            name='total_device_count',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='room',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='device',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterModelTable(
            name='room',
            table='Room',
        ),
    ]
