# Generated by Django 5.0.3 on 2024-05-21 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booklist', '0015_alter_room_options_remove_room_device_device_room_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sensor',
            options={'ordering': ['name'], 'verbose_name': 'Sensor', 'verbose_name_plural': 'Sensor'},
        ),
        migrations.AlterModelTable(
            name='sensor',
            table='Sensor',
        ),
    ]
