# Generated by Django 5.0.3 on 2024-05-21 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklist', '0016_alter_sensor_options_alter_sensor_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='total_device_count',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
