# Generated by Django 5.0.3 on 2024-05-21 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklist', '0017_alter_room_total_device_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
