# Generated by Django 5.0.3 on 2024-05-22 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklist', '0018_alter_room_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='data_type',
            field=models.CharField(default='bit', max_length=255),
        ),
    ]
